# Generated by Django 5.2.5 on 2025-08-12 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ldap_dn",
                    models.TextField(
                        blank=True,
                        help_text="Active DirectoryのDistinguished Name",
                        verbose_name="LDAP DN",
                    ),
                ),
                (
                    "department_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="所属コード"
                    ),
                ),
                (
                    "department_name",
                    models.CharField(blank=True, max_length=100, verbose_name="所属名"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=100, verbose_name="役職"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ユーザープロファイル",
                "verbose_name_plural": "ユーザープロファイル",
            },
        ),
    ]
