# Generated by Django 5.2.5 on 2025-08-12 10:44

import applications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=applications.models.get_upload_path,
                        verbose_name="ファイル",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="元ファイル名"),
                ),
                ("file_size", models.IntegerField(verbose_name="ファイルサイズ")),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="コンテンツタイプ"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="申請コメント")),
                (
                    "approval_comment",
                    models.TextField(blank=True, verbose_name="承認コメント"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "申請中"),
                            ("approved", "承認済み"),
                            ("rejected", "却下"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="ステータス",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="承認日時"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申請者",
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="承認者",
                    ),
                ),
            ],
            options={
                "verbose_name": "申請",
                "verbose_name_plural": "申請",
                "ordering": ["-created_at"],
            },
        ),
    ]
