# Generated by Django 5.2.5 on 2025-08-12 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="アクション")),
                ("details", models.TextField(verbose_name="詳細")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="実行日時"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.application",
                        verbose_name="対象申請",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="実行ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "監査ログ",
                "verbose_name_plural": "監査ログ",
                "ordering": ["-created_at"],
            },
        ),
    ]
